### ISSUE TITLE
strictness of conversion rules

### ISSUE THREAD

**Issue by grindhold** [crazycodr/roman#2]
I just discovered, that roman will happily convert "IVM" to 1004 .
I am not an expert regarding roman numbers, but I thought there is a strict left-to-right notation. From most significant characters to least significant characters, so

MIV → legit
IVM → not legit

I'd like to know wheter this behaviour is intentional or not.
A quick research yielded no hints to any occurences of numbers in the style above.

Thanks in advance and thanks for this useful module

**Comment by wandersonwhcr** [comment]
@grindhold https://github.com/wandersonwhcr/romans

**Comment by crazycodr** [comment]
Hey, i actually don't use that library anymore. I created that like 2-3 years ago? My goal was not to create a super complex system that validates, just a way to easily convert one to one.
